package org.edgexfoundry.rules;
global org.edgexfoundry.engine.CommandExecutor executor;
global org.edgexfoundry.support.logging.client.EdgeXLogger logger;
import org.edgexfoundry.domain.core.Event;
import org.edgexfoundry.domain.core.Reading;
import java.util.Map;
rule "motortoofastsignal" 
when
  $e:Event($rlist: readings && device=="562114e9e4b0385849b96cd8")
  $r0:Reading(name=="RPM" && Integer.parseInt(value) > 1200) from $rlist
then
executor.fireCommand("56325f7ee4b05eaae5a89ce1", "56325f6de4b05eaae5a89cdc", "{\"value\":\"3\"}");
logger.info("Patlite warning triggered for engine speed too high");
end